name: Devel image build test

on:
  # allow triggering this workflow manually
  workflow_dispatch:
  # run this workflow on Sat at 6 am for the default branch
  schedule:
    - cron: "5 6 * * 6"
  # Note: This is intentionally not triggering a full rebuild for PRs or main/devel
  # push events because of the large run-time.

jobs:
  build_development_environment:
    name: Building devel environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Run docker image build script
        run: |
          cd docker
          ./build.bash
